// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfZHaf1o2QiA3q3i5Ne8khC9W0QcKV_FE',
    appId: '1:74676319669:web:e7edcbc7235bf74e3815fc',
    messagingSenderId: '74676319669',
    projectId: 'citizen-voting-app',
    authDomain: 'citizen-voting-app.firebaseapp.com',
    storageBucket: 'citizen-voting-app.firebasestorage.app',
    measurementId: 'G-MFFNHR161D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnyAAnyPTQSRqRzH8rKBHT3xHxZzBfWCY',
    appId: '1:74676319669:android:ff8fc6fbdac92e6b3815fc',
    messagingSenderId: '74676319669',
    projectId: 'citizen-voting-app',
    storageBucket: 'citizen-voting-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS3fKl5qmZM3K_gCsIbk6Xk85yCGiMhZQ',
    appId: '1:74676319669:ios:000f9442efde01f03815fc',
    messagingSenderId: '74676319669',
    projectId: 'citizen-voting-app',
    storageBucket: 'citizen-voting-app.firebasestorage.app',
    iosBundleId: 'com.example.citizenVotingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS3fKl5qmZM3K_gCsIbk6Xk85yCGiMhZQ',
    appId: '1:74676319669:ios:000f9442efde01f03815fc',
    messagingSenderId: '74676319669',
    projectId: 'citizen-voting-app',
    storageBucket: 'citizen-voting-app.firebasestorage.app',
    iosBundleId: 'com.example.citizenVotingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfZHaf1o2QiA3q3i5Ne8khC9W0QcKV_FE',
    appId: '1:74676319669:web:5d293a5b2c004a683815fc',
    messagingSenderId: '74676319669',
    projectId: 'citizen-voting-app',
    authDomain: 'citizen-voting-app.firebaseapp.com',
    storageBucket: 'citizen-voting-app.firebasestorage.app',
    measurementId: 'G-4BL2194R6N',
  );

}